export const columnsConfiguration = [
    {
       "Header":"ID",
       "id":"_id",
       "accessor":"_id",
       "disableFilters":true,
       "disableSortBy":true
    },
    {
       "Header":"LABEL",
       "id":"label",
       "accessor":"label",
       "filter":{
          "type":"string"
       }
    },
    {
       "Header":"DESC",
       "id":"desc",
       "accessor":"desc",
       "filter":{
          "type":"string"
       }
    },
    {
       "Header":"MODEL",
       "id":"model",
       "accessor":"model",
       "filter":{
          "type":"string"
       }
    },
    {
       "Header":"MANUFACTURER",
       "id":"manufacturer",
       "accessor":"manufacturer",
       "filter":{
          "type":"string"
       }
    },
    {
       "Header":"COST_IN_CREDITS",
       "id":"cost_in_credits",
       "accessor":"cost_in_credits",
       "filter":{
          "type":"number"
       }
    },
    {
       "Header":"LENGTH",
       "id":"length",           
       "accessor":"length",
       "filter":{
          "type":"string"
       }
    },
    {
       "Header":"MAX_ATMOSPHERING_SPEED",
       "id":"max_atmosphering_speed",
       "accessor":"max_atmosphering_speed",
       "filter":{
          "type":"number"
       }
    },
    {
       "Header":"CREW",
       "id":"crew",
       "accessor":"crew",
       "filter":{
          "type":"string"
       }
    },
    {
       "Header":"PASSENGERS",
       "id":"passengers",
       "accessor":"passengers",
       "filter":{
          "type":"string"
       }
    },
    {
       "Header":"CARGO_CAPACITY",
       "id":"cargo_capacity",
       "accessor":"cargo_capacity",
       "filter":{
          "type":"number"
       }
    },
    {
       "Header":"CONSUMABLES",
       "id":"consumables",
       "accessor":"consumables",
       "filter":{
          "type":"string"
       }
    },
    {
       "Header":"HYPERDRIVE_RATING",
       "id":"hyperdrive_rating",
       "accessor":"hyperdrive_rating",
       "filter":{
          "type":"string"
       }
    },
    {
       "Header":"MGLT",
       "id":"MGLT",
       "accessor":"MGLT",
       "filter":{
          "type":"string"
       }
    },
    {
       "Header":"STARSHIP_CLASS",
       "id":"starship_class",
       "accessor":"starship_class",
       "filter":{
          "type":"string"
       }
    },
    {
       "Header":"CREATED",
       "id":"created",
       "accessor":"created",
       "filter":{
          "type":"string"
       },
       "disableFilters":true,
       "disableSortBy":true
    },
    {
       "Header":"EDITED",
       "id":"edited",
       "accessor":"edited",
       "filter":{
          "type":"string"
       },
       "disableFilters":true,
       "disableSortBy":true
    },
    {
       "Header":"URL",
       "id":"url",
       "accessor":"url",
       "filter":{
          "type":"string"
       }
    }
 ]